// src/components/EducationSection.vue
<script setup>
import { useOpenLink } from '@/use/openLink'

const options = [
  {
    title: 'Master of Engineering, Electrical and Computer Engineering',
    name: 'Tamkang University',
    content: 'Thesis - Hardware/Software Co-Design of Pick and Place Operations for Path Planning',
    time: 'Feb. 2011 ~ Jan. 2014',
  },
  {
    title: 'Short-term Exchange Study Program - JUSST',
    name: 'Miracle Information Technology Inc.',
    content: 'Japanese University Studies in Science & Technology (JUSST)',
    time: 'Apr. 2012 ~ Mar. 2013',
    link: ['JUSST', 'http://www.fedu.uec.ac.jp/en/future_students/jusst/'],
  },
  {
    title: 'Bachelor of Engineering, Electrical and Computer Engineering',
    name: 'Tamkang University',
    content: '',
    time: 'Sep. 2006 ~ Jan. 2011',
  },
]
</script>

<template>
  <div class="section">
    <n-h3 id="education">Education</n-h3>

    <n-timeline class="mt-4">
      <n-timeline-item
        v-for="item in options"
        :key="item.name"
        :title="item.title"
        :content="item.content"
        :time="item.time"
      >
        <template #default>
          <div class="text-xs italic">{{ item.name}}</div>
          <div class="mt-1">{{ item.content }}</div>
          <n-button
            v-if="item.link"
            class="mt-1"
            size="tiny"
            @click="useOpenLink(item.link[1])"
          >
            {{ item.link[0] }}
          </n-button>
        </template>
      </n-timeline-item>
    </n-timeline>
  </div>
</template>

// src/components/education/EducationSection.tsx
import { Fragment, memo } from 'react'
import clsx from 'clsx'
import SectionTitle from '../generic/SectionTitle'
import ExperienceCard from '../generic/ExperienceCard'
import uecLogo from '@/assets/logo/uec-logo.jpeg'
import tkuLogo from '@/assets/logo/tku-logo.jpeg'
import type { ExperienceConfig } from '@/_types'

const educationConfig: ExperienceConfig[] = [
  {
    role: ['Master of Engineering, Electrical and Computer Engineering'],
    place: 'Tamkang University (TKU), New Taipei',
    description:
      'Thesis - Hardware/Software Co-Design of Pick and Place Operations for Path Planning',
    duration: 'Feb. 2011 ~ Jan. 2014',
    devStack: [
      'Path Planning Optimization',
      'Ant Colony Optimization (ACO) algorithm',
      'Motion Control Design',
    ],
    image: tkuLogo,
  },
  {
    role: ['Short-term Exchange Study Program - JUSST'],
    place: 'The University of Electro-Communications (UEC), Tokyo',
    description:
      'Japanese University Studies in Science & Technology (JUSST) Program',
    duration: 'Apr. 2012 ~ Mar. 2013',
    link: [
      ['JUSST Program', 'http://www.fedu.uec.ac.jp/en/future_students/jusst/'],
    ],
    image: uecLogo,
  },
  {
    role: ['Bachelor of Engineering, Electrical and Computer Engineering'],
    place: 'Tamkang University (TKU), New Taipei',
    description: '',
    duration: 'Sep. 2006 ~ Jan. 2011',
    image: tkuLogo,
  },
]

const EducationSection = memo(() => {
  return (
    <>
      <SectionTitle
        title='Education'
        hashId='education'
      />

      <div className={clsx('flex flex-col gap-4')}>
        {educationConfig.map((item: any, index: number) => (
          <Fragment key={index}>
            <ExperienceCard experience={item} />
          </Fragment>
        ))}
      </div>
    </>
  )
})

export default EducationSection
