// src/components/PlaygroundSection.vue
<script setup>
import { useOpenLink } from '@/use/openLink'
import vue3TodoListImage from '@/assets/playground/vue3-todolist.png'
import reactWeatherAppImage from '@/assets/playground/react-weather-app.png'

const playgroundList = [
  {
    id: 'vue3-todolist',
    title: 'Vue3 Todo List',
    content: 'A Todo List is created with Vue3, Vite, Typescript and TailwindCSS.',
    image: vue3TodoListImage,
    href: 'https://master.d2o7cksds4b7ta.amplifyapp.com/',
  },
  {
    id: 'react-weather-app',
    title: 'React Weather App',
    content: 'Build up a simple app with React.js & Redux for checking the weather of major cities in Taiwan.',
    image: reactWeatherAppImage,
    href: 'https://eyvindove.github.io/react-weather/',
  },
]
</script>

<template>
  <div class="section">
    <n-h3 id="playground">Playground</n-h3>

    <div class="flex flex-wrap justify-center md:justify-start gap-4">
      <n-card
        v-for="item in playgroundList"
        :key="item.id"
        class="w-[300px] max-h-[360px]"
      >
        <template #cover>
          <n-image :src="item.image" />
        </template>

        <template #header>
          <div>{{ item.title }}</div>
        </template>

        <template #default>
          <div>{{ item.content }}</div>
          <n-button class="mt-4" @click="useOpenLink(item.href)">Live Demo</n-button>
        </template>
      </n-card>
    </div>
  </div>
</template>

// src/components/playground/PlaygroundSection.tsx
import { Fragment, memo } from 'react'
import clsx from 'clsx'
import SectionTitle from '../generic/SectionTitle'
import PlaygroundCard from './PlaygroundCard'
import reactWeatherImage from '@/assets/playground/react-weather.png'
import vue3TodoListImage from '@/assets/playground/vue3-todolist.png'
import type { PlaygroundConfig } from '@/_types'

const playgroundConfig: PlaygroundConfig[] = [
  {
    id: 'react-weather',
    title: 'React Weather App',
    description:
      'A weather app for checking weather information of major cities in the world, which is built by React, TypeScript, Vite, and Mantine UI.',
    image: reactWeatherImage,
    demo: 'https://react-weather-eyvindove.vercel.app/',
    github: 'https://github.com/eyvindove/react-weather',
  },
  {
    id: 'vue3-todolist',
    title: 'Vue3 Todo List',
    description:
      'A Todo List with basic functions, which is built by Vue3, Typescript, Vite and TailwindCSS.',
    image: vue3TodoListImage,
    demo: 'https://vue3-todolist-eyvindove.vercel.app/',
    github: 'https://github.com/eyvindove/vue3-todolist',
  },
]

const PlaygroundSection = memo(() => {
  return (
    <>
      <SectionTitle
        title='Playground'
        hashId='playground'
      />

      <div className={clsx('flex flex-row flex-wrap gap-2')}>
        {playgroundConfig.map((item: any, index: number) => (
          <Fragment key={index}>
            <PlaygroundCard playground={item} />
          </Fragment>
        ))}
      </div>
    </>
  )
})

export default PlaygroundSection
