// src/components/work-experience/WorkExperienceSection.tsx
import { Fragment, memo } from 'react'
import clsx from 'clsx'
import SectionTitle from '../generic/SectionTitle'
import ExperienceCard from '../generic/ExperienceCard'
import efaiLogo from '@/assets/logo/everfortuneai-logo.jpeg'
import ohbotLogo from '@/assets/logo/ohbot-logo.jpeg'
import miracleLogo from '@/assets/logo/miracle-logo.jpeg'
import adlinkLogo from '@/assets/logo/adlink-logo.jpeg'
import type { ExperienceConfig } from '@/_types'

const workExperienceConfig: ExperienceConfig[] = [
  {
    role: ['Software Developer'],
    place: 'Ever Fortune.AI',
    duration: 'Aug. 2022 ~ now',
    description:
      'Build and develop next generation genetic testing analysis web applications with React.js ecosystem, responsible for admin CMS and client-side website. Refactor released genetic testing analysis web application from Vue.js to React.js. Maintain partial analysis report PDF generator with Python.',
    devStack: [
      'React',
      'Vue',
      'TypeScript',
      'Vite',
      'TailwindCSS',
      'GitLab CICD',
      'Python',
    ],
    image: efaiLogo,
  },
  {
    role: ['Frontend Web Developer'],
    place: 'Oh!Bot Sien Technology',
    description:
      'Developed and improved social CRM SaaS applications with Vue.js ecosystem, responsible for admin CMS, reservation product, customized project and official website.',
    duration: 'Dec. 2021 ~ Jun. 2022',
    devStack: [
      'Vue3',
      'Vue2',
      'JavaScript',
      'Vite',
      'TailwindCSS',
      'GitLab CI',
      'Jira',
    ],
    image: ohbotLogo,
  },
  {
    role: ['Senior Frontend Developer', 'Frontend Developer'],
    place: 'Miracle Information Technology',
    description:
      'Developed and improved client-side website and admin dashboard applications with Vue.js ecosystem.',
    duration: 'Jul. 2019 ~ Dec. 2020',
    devStack: [
      'Vue2',
      'JavaScript',
      'Webpack',
      'SCSS',
      'Pug',
      'GitLab CI',
      'Scrum',
    ],
    image: miracleLogo,
  },
  {
    role: ['Senior FPGA Engineer', 'FPGA Engineer'],
    place: 'ADLINK Technology',
    description:
      'Designed, implemented and verified FPGA centric solutions for modular instrument products, responsible for frame grabber, data acquisition and digitizer products.',
    duration: 'Jul. 2015 ~ Oct. 2018',
    devStack: [
      'Verilog HDL',
      'FPGA',
      'ModelSim',
      'Algorithm Development',
      'Shell Script',
      'Jira',
    ],
    image: adlinkLogo,
  },
]

const WorkExperienceSection = memo(() => {
  return (
    <>
      <SectionTitle
        title='Work Experience'
        hashId='work-experience'
      />

      <div className={clsx('flex flex-col gap-4')}>
        {workExperienceConfig.map((item: any, index: number) => (
          <Fragment key={index}>
            <ExperienceCard experience={item} />
          </Fragment>
        ))}
      </div>
    </>
  )
})

export default WorkExperienceSection

// src/components/WorkExperienceSection.vue
<script setup>
import { CheckmarkOutline } from '@vicons/carbon'
const options = [
  {
    title: 'Frontend Web Developer',
    name: 'Oh!Bot Sien Technology Inc.',
    content: 'Develop and improve social CRM SaaS services with Vue.js, responsible for admin dashboard, member management, reservation products, customized project and official website.',
    time: 'Dec. 2021 ~ Jun. 2022',
    stack: ['Vue3', 'Vue2', 'Vite', 'JavaScript', 'TailwindCSS', 'GitLab CI', 'Jira'],
  },
  {
    title: 'Senior Frontend Developer',
    name: 'Miracle Information Technology Inc.',
    content: 'Develop and improve member management and admin dashboard services with Vue.js.',
    time: 'Jul. 2019 ~ Dec. 2020',
    stack: ['Vue2', 'JavaScript', 'Webpack', 'SCSS', 'Pug', 'Scrum'],
  },
  {
    title: 'Senior FPGA Engineer <<< FPGA Engineer',
    name: 'ADLINK Technology Inc.',
    content: 'Design, implement and verify FPGA centric solutions for modular instrument products, responsible for frame grabber, data acquisition and digitizer products.',
    time: 'Jul. 2015 ~ Oct. 2018',
    stack: ['Verilog HDL', 'FPGA', 'ModelSim', 'Algorithm Development', 'Shell', 'Jira'],
  },
]
</script>

<template>
  <div class="section">
    <n-h3 id="work-experience">Work Experience</n-h3>

    <n-timeline class="mt-4">
      <n-timeline-item
        v-for="item in options"
        :key="item.name"
        :title="item.title"
        :content="item.content"
        :time="item.time"
      >
        <template #default>
          <div class="text-xs italic">{{ item.name}}</div>
          <div class="mt-1">{{ item.content }}</div>

          <n-tag
            v-for="subItem in item.stack"
            :key="subItem"
            class="mt-2 mr-2"
            round
            size="small"
            type="success"
            :bordered="false"
          >
            {{ subItem }}
            <template #icon>
              <n-icon :component="CheckmarkOutline" />
            </template>
          </n-tag>
        </template>
      </n-timeline-item>
    </n-timeline>
  </div>
</template>
